package com.aregyan.compose.network.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Rates(
    @Json(name = "AED")
    val aED: Double,
    @Json(name = "AFN")
    val aFN: Double,
    @Json(name = "ALL")
    val aLL: Double,
    @Json(name = "AMD")
    val aMD: Double,
    @Json(name = "ANG")
    val aNG: Double,
    @Json(name = "AOA")
    val aOA: Double,
    @Json(name = "ARS")
    val aRS: Double,
    @Json(name = "AUD")
    val aUD: Double,
    @Json(name = "AWG")
    val aWG: Double,
    @Json(name = "AZN")
    val aZN: Double,
    @Json(name = "BAM")
    val bAM: Double,
    @Json(name = "BBD")
    val bBD: Double,
    @Json(name = "BDT")
    val bDT: Double,
    @Json(name = "BGN")
    val bGN: Double,
    @Json(name = "BHD")
    val bHD: Double,
    @Json(name = "BIF")
    val bIF: Double,
    @Json(name = "BMD")
    val bMD: Double,
    @Json(name = "BND")
    val bND: Double,
    @Json(name = "BOB")
    val bOB: Double,
    @Json(name = "BRL")
    val bRL: Double,
    @Json(name = "BSD")
    val bSD: Double,
    @Json(name = "BTC")
    val bTC: Double,
    @Json(name = "BTN")
    val bTN: Double,
    @Json(name = "BWP")
    val bWP: Double,
    @Json(name = "BYN")
    val bYN: Double,
    @Json(name = "BYR")
    val bYR: Double,
    @Json(name = "BZD")
    val bZD: Double,
    @Json(name = "CAD")
    val cAD: Double,
    @Json(name = "CDF")
    val cDF: Double,
    @Json(name = "CHF")
    val cHF: Double,
    @Json(name = "CLF")
    val cLF: Double,
    @Json(name = "CLP")
    val cLP: Double,
    @Json(name = "CNY")
    val cNY: Double,
    @Json(name = "COP")
    val cOP: Double,
    @Json(name = "CRC")
    val cRC: Double,
    @Json(name = "CUC")
    val cUC: Double,
    @Json(name = "CUP")
    val cUP: Double,
    @Json(name = "CVE")
    val cVE: Double,
    @Json(name = "CZK")
    val cZK: Double,
    @Json(name = "DJF")
    val dJF: Double,
    @Json(name = "DKK")
    val dKK: Double,
    @Json(name = "DOP")
    val dOP: Double,
    @Json(name = "DZD")
    val dZD: Double,
    @Json(name = "EGP")
    val eGP: Double,
    @Json(name = "ERN")
    val eRN: Double,
    @Json(name = "ETB")
    val eTB: Double,
    @Json(name = "EUR")
    val eUR: Int,
    @Json(name = "FJD")
    val fJD: Double,
    @Json(name = "FKP")
    val fKP: Double,
    @Json(name = "GBP")
    val gBP: Double,
    @Json(name = "GEL")
    val gEL: Double,
    @Json(name = "GGP")
    val gGP: Double,
    @Json(name = "GHS")
    val gHS: Double,
    @Json(name = "GIP")
    val gIP: Double
    // TODO add other values
)